query Search($query: String!) {
    search(query: $query) {
        ... on UndergraduateStudent {
            id
            name
            email
            enrollmentStatus: status
            major
        }
        ... on GraduateStudent {
            id
            name
            email
            enrollmentStatus: status
            department
            thesisTitle
        }
        ... on Course {
            id
            code
            title
            credits
            courseStatus: status
        }
        ... on Instructor {
            id
            name
            email
            department
        }
    }
}
